# This workflow creates docker images that are then used for:
#
# - DIRAC distribution (create DIRAC release tarballs)
# - running DIRAC integration tests in GitHub actions (slc6+cc7+c8)
# 
# All created images are then uploaded to GitHub packages and docker hub

name: Create images

on:
  push:
  schedule:
    # every Sunday
    - cron:  '0 0 * * 0'

jobs:
  # Image for running dirac-distribution
  dirac-distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          echo $PWD
          ls -l
          docker build -t dirac-distribution dirac-distribution/
      - name: tag
        run: |
          docker tag dirac-distribution diracgrid/dirac-distribution:latest
          docker tag dirac-distribution docker.pkg.github.com/diracgrid/management/dirac-distribution:latest
      - name: show
        run: docker images
      - name: login and push
        env:
          deploy_secret: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          if [ -z ${deploy_secret} ]
          then
            echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
            docker push diracgrid/dirac-distribution:latest
            docker push docker.pkg.github.com/diracgrid/management/dirac-distribution:latest
          else 
            echo "Skipping deploy: no secrets present"
          fi